# Generated by Django 5.2.12 on 2026-03-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alphagroup',
            name='display_name',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alphagroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
