# Generated by Django 5.2.12 on 2026-03-28 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alphagroup_display_name_alphagroup_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('remarks', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('amount_a', models.FloatField(default=0)),
                ('amount_b', models.FloatField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('alpha_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.alphagroup')),
            ],
        ),
    ]
