# Generated by Django 5.2.12 on 2026-03-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_voucher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='date',
            new_name='voucher_date',
        ),
    ]
