# Generated by Django 5.2.12 on 2026-03-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_date_voucher_voucher_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='amount_a',
            new_name='total_a',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='amount_b',
            new_name='total_b',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='alpha_group',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='type',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='remarks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_no',
            field=models.CharField(max_length=50),
        ),
    ]
